### ISSUE TITLE
Training on 2 RTX3090 GPUs shows significant performance degradation.

### ISSUE THREAD

**Issue by jianghaojun** [fjhzhixi/3D-SPS#2]
Running the training program on a single RTX3090 will encounter the out of memory problem. Thus, I run the code in the distributed mode with 2 RTX3090, and the batchsize is 16 for each GPU(total batchsize = 2 x 16). 

I change the following code:
```
### TODO: Following is original code. The broadcast_buffers is set to False which disable the batchnorm to sync between GPUs. https://discuss.pytorch.org/t/do-nn-batchnorm-in-distributed-training-default-to-be-synchronized/42140
# model = DistributedDataParallel(model, device_ids=[args.local_rank], broadcast_buffers=False,
#                                 find_unused_parameters=True)
### End
model = DistributedDataParallel(model, device_ids=[args.local_rank], broadcast_buffers=True,
                                find_unused_parameters=True)
```

All other parameters and setting remain the same.

After training 32 epoch, I got much lower results compared to the paper. Since there is a *args.distribute* parameter exist in the training code, I hope authors could give me some help with this problem.

```
unique:
unique | not_in_others | ref_acc: 0.1271611823759063
unique | not_in_others | acc@0.25iou: 0.7233686558839934
unique | not_in_others | acc@0.5iou: 0.5504740658114892
unique | in_others | ref_acc: 0.25
unique | in_others | acc@0.25iou: 0.7692307692307693
unique | in_others | acc@0.5iou: 0.6538461538461539
unique | overall | ref_acc: 0.13062330623306234
unique | overall | acc@0.25iou: 0.7246612466124661
unique | overall | acc@0.5iou: 0.5533875338753388

multiple:
multiple | not_in_others | ref_acc: 0.07348242811501597
multiple | not_in_others | acc@0.25iou: 0.3112733911455956
multiple | not_in_others | acc@0.5iou: 0.24965769055225925
multiple | in_others | ref_acc: 0.18043279487960986
multiple | in_others | acc@0.25iou: 0.4001828710758915
multiple | in_others | acc@0.5iou: 0.2694300518134715
multiple | overall | ref_acc: 0.1192744355996346
multiple | overall | acc@0.25iou: 0.34934098916873285
multiple | overall | acc@0.5iou: 0.2581234503458176

overall:
overall | not_in_others | ref_acc: 0.08906882591093117
overall | not_in_others | acc@0.25iou: 0.43093117408906884
overall | not_in_others | acc@0.5iou: 0.33700404858299593
overall | in_others | ref_acc: 0.18151815181518152
overall | in_others | acc@0.25iou: 0.40594059405940597
overall | in_others | acc@0.5iou: 0.27542754275427545
overall | overall | ref_acc: 0.12147665124106016
overall | overall | acc@0.25iou: 0.4221708035338662
overall | overall | acc@0.5iou: 0.31541859486748003
```

**Comment by fjhzhixi** [comment]
As we stated in the implementation details of our paper, we adopt the pretrained PointNet++ backbone whose path is defined in the config file. Sorry for the omission before and now we have updated the download path of this backbone, please try training with the pre-trained backbone.

**Comment by jianghaojun** [comment]
Thanks for the quick reply. I will try to train the model with the pre-trained PointNet++.

**Comment by jianghaojun** [comment]
I re-train the model with pre-trained PointNet++ and get much better performance. But I encounter a problem of training instability where training loss increases steeply several times.

I guess it could be a problem with ```num_workers```. When I set the ```num_workers = 2```, the instability Instability becomes more pronounced. And I notice the default setting is ```num_workers = 0```.

Did authors encounter this problem?

**Comment by jianghaojun** [comment]
I re-train the model with pre-trained PointNet++ and the final performance is Overall IoU@0.5 **34.42**(Input 3D only) which is still 2.01 lower than paper.

**Training Settings:**
- Devices: 2 * RTX 3090. 
- Distributed training. 
- Batchsize for each GPU is 16. Total batchsize is 32.
- Num_workers = 1. Using num_worker=0 get even worse performance, Overall IoU@0.5 **32.53**(Input 3D only).
- Other hyper-parameters are kept same as default: 
    ```
    GENERAL:
      manual_seed: 3407
      tag: reproduce_wo-multiview_with-pretrained-pointnet++_workers-1
      gpu: '0'
      debug: False
      distribute: True
    
    PATH:
      root_path: '/cluster/home/hjjiang/20220606/SPS/'
      scannet_data_root: '/home/data/ScanRefer/data/'
      scanref_data_root: '/home/data/ScanRefer/data/'
    
    DATA:
      dataset: ScanRefer
      num_points: 40000
      num_scenes: -1
      num_classes: 20
      use_augment: False
      max_num_obj: 128
    
      # input
      use_height: False
      use_color: True
      use_normal: True
      use_multiview: False
      fuse_multi_mode: late   # early or late
    
      # label
      det_class_label: main_with_others    # all, main_with_others, main
    
    MODEL:
      # general
      dropout: 0.1
      use_checkpoint: False
    
      # point backbone
      point_feat_dim: 288
    
      # visual feature
      vis_feat_dim: 128
      
      # sampling
      sampling: kpsa-lang-filter
      num_proposal: 512
      kps_fusion_dim: 256
      use_ref_score_loss: True
      use_context_label: False
      ref_use_obj_mask: True
      
      # Head
      size_cls_agnostic: False
      use_objectness: True
    
      # Language Module
      lang_emb_type: clip
      max_des_len: 77
      word_erase: 0.1
      #embedding_size: 300
      #gru_hidden_size: 256
      #gru_num_layer: 1
      #use_bidir: False # bi-directional GRU
    
      # Transformer
      model: 'TransformerFilter'
      num_decoder_layers: 5
      object_position_embedding: loc_learned
      point_position_embedding: xyz_learned
      lang_position_embedding: none
      transformer_feat_dim: 384
      ffn_dim: 2048
      n_head: 4
      transformer_dropout: 0.05
      use_ref_mask: False
      use_att_score: True
      ref_filter_steps: [1,2,3,4]
      ref_mask_scale: 0.5
      transformer_mode: serial
    
      # pretrain
      use_pretrained: True
      pretrain_path: '/cluster/home/hjjiang/20220606/SPS/xyz_rgb_norm_backbone.pth'
      trans_pre_model: False
    
    LOSS:
      # ----- Refer -----
      no_detection: False
      no_reference: False
      no_lang_cls: False
      ref_each_stage: True
      cls_each_stage: True
      ref_criterion: rank
      # ----- Detection -----
      kps_topk: 5
      kps_loss_weight: 0.8
      det_loss_weight: 5
      center_delta: 0.04
      size_delta: 0.111111111111
      heading_delta: 1
    
    TRAIN:
      batch_size: 16
      num_workers: 1
      epoch: 32
    
      lr: 0.001
      decoder_lr: 0.0001
      det_decoder_lr: False
      lr_decay_step: [16, 24, 28]
      lr_decay_rate: 0.1
      bn_decay_step: 10
      bn_decay_rate: 0.1
      bn_momentum_init: 0.2
      bn_momentum_min: 0.001
      wd: 0.0005
    
      verbose: 20       # iter num to ouput log in shell
      val_freq: 2       # epoch num to val
      eval_det: True
      eval_ref: True
      iou_ref_th: 0.25
      iou_ref_topk : 4
    ```

**Comment by luo-junyu** [comment]
Hi @jianghaojun , 
1. As for the parameter `num_worker`, we set `num_worker = 0` due to the limitation of memory and CPU. So we didn't encounter the problem of `num_worker`.
2. Distributed training. As mentioned in the paper, the experiments are implemented on a single GPU card. Actually, we didn't utilize the distributed training codes from the original repo.

**Comment by jianghaojun** [comment]
> Hi @jianghaojun ,
> 
> 1. As for the parameter `num_worker`, we set `num_worker = 0` due to the limitation of memory and CPU. So we didn't encounter the problem of `num_worker`.
> 2. Distributed training. As mentioned in the paper, the experiments are implemented on a single GPU card. Actually, we didn't utilize the distributed training codes from the original repo.

Thanks for replying. I will try to explore the reason for this phenomenon.

**Comment by jianghaojun** [comment]
I try to train the model with multiview features and get **overall IoU@0.25/IoU@0.5=48.86/36.91**.

**Training Settings**:

- Devices: 2 * RTX 3090.
- Distributed training.
- Batchsize for each GPU is 16. Total batchsize is 32.
- Num_workers = 1. 
- Learning rate as default.
- **Replace the StepLR with Cosine schedule.**

**Comment by Joyce-lovenature** [comment]
Hi @jianghaojun ,

**Comment by JoycexxZ** [comment]
Hi @jianghaojun ,
I encountered the same problem on about 2 points lower. What parameters did you set when using cosine schedule?

**Comment by jianghaojun** [comment]
@Joyce-lovenature The learning rate is kept same as default. 

When I only use 3D information, the best overall IoU@0.5 I can get is around 35.

When I use 2D+3D information, the best overall IoU@0.5 I can get is 36.91(reported in above).

**Comment by Zhang-Jing-Xuan** [comment]
Hi @jianghaojun ,
When you are training on 2 RTX3090, can you release your training command and train.py? Thanks.

**Comment by Sxx1995** [comment]
> I try to train the model with multiview features and get **overall IoU@0.25/IoU@0.5=48.86/36.91**.
> 
> **Training Settings**:
> 
> * Devices: 2 * RTX 3090.
> * Distributed training.
> * Batchsize for each GPU is 16. Total batchsize is 32.
> * Num_workers = 1.
> * Learning rate as default.
> * **Replace the StepLR with Cosine schedule.**

@jianghaojun Is that CosineAnnealingLR function in torch.optim.lr_scheduler?

**Comment by jianghaojun** [comment]
@Sxx1995 I use following cosine schedule.
```
lr_func = lambda epoch: 0.5 * (1. + math.cos(math.pi * epoch / args.epochs))
scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_func)
```

**Comment by sunanhe** [comment]
> I try to train the model with multiview features and get **overall IoU@0.25/IoU@0.5=48.86/36.91**.
> 
> **Training Settings**:
> 
> * Devices: 2 * RTX 3090.
> * Distributed training.
> * Batchsize for each GPU is 16. Total batchsize is 32.
> * Num_workers = 1.
> * Learning rate as default.
> * **Replace the StepLR with Cosine schedule.**

Hi, how long does it take to train on 2 RTX3090？

**Comment by jianghaojun** [comment]
@seanhe97 Hi, it takes almost 25h.

**Comment by Zhang-Jing-Xuan** [comment]
@jianghaojun Hi, after I finished training on 2 RTX3090s, I got an error when I tried to evaluate the model. 
It says: RuntimeError: Error(s) in loading state_dict for VGNet，Missing key(s) in state_dict: "backbone_net.sa1.mlp_module.layer0.conv.weight", "backbone_net.sa1.mlp_module.layer0.bn.bn.weight",...
Have you changed any code in eval.py to solve this problem? Thanks.

**Comment by jianghaojun** [comment]
@Zhang-Jing-Xuan Hi, I am sorry that I have no idea about this error.

To the best of my knowledge, training with multiple GPUs will only add ".module" to the name of all the weights which might cause the missing error.

You can create an issue to ask authors about this error.

**Comment by Zhang-Jing-Xuan** [comment]
> @Zhang-Jing-Xuan Hi, I am sorry that I have no idea about this error.
> 
> To the best of my knowledge, training with multiple GPUs will only add ".module" to the name of all the weights which might cause the missing error.
> 
> You can create an issue to ask authors about this error.

Thanks, I know what the bug is. I have solved this problem.
