### ISSUE TITLE
what is the pretrain_path should be in the default yaml

### ISSUE THREAD

**Issue by Sxx1995** [fjhzhixi/3D-SPS#3]
I met the error when using the default.yaml to train the model. the use_pretrain is set as true in the yaml while no path has been given out. What is the pretrained model and where I can find that?

**Comment by jianghaojun** [comment]
Download pre-trained model from the link in [README](https://github.com/fjhzhixi/3D-SPS#:~:text=Download%20the%20pre%2Dtrained%20PointNet%2B%2B%20backbone%20(Google%20Drive%20or%20Baidu%20Drive(passcode%3A%20likl)%5D))

**Comment by Sxx1995** [comment]
Which model do you mean, PointNet++ backbone, CLIP/GLoVe embedding or entire pretrained model?

**Comment by fjhzhixi** [comment]
Here using pretrain means using pre-trained PointNet++ backbone
