### ISSUE TITLE
 Nr3D/Sr3D datasets

### ISSUE THREAD

**Issue by Zhang-Jing-Xuan** [fjhzhixi/3D-SPS#7]
Can you also release code for Nr3D/Sr3D training and evaluation? There is evaluation results for Nr3D/Sr3D in your paper. Thanks.

**Comment by fjhzhixi** [comment]
We implement our method based on the [SAT](https://github.com/zyang-ur/SAT) and experiment on Nr3D/Sr3D, you can refer to the core code of this codebase and adapt it to the SAT codebase.
