### ISSUE TITLE
Where  should the downloaded pre-trained PointNet++ backbone be put in the step 5?

### ISSUE THREAD

**Issue by Ivan-Tang-3D** [fjhzhixi/3D-SPS#9]
Sorry, I wonder where(Which path) should i put the pre-trained PointNet++ backbone mentioned in the step 5?

**Comment by fjhzhixi** [comment]
You can put it anywhere you can access and set the corresponding path in the item `pretrain_path` in config file.

**Comment by Ivan-Tang-3D** [comment]
OKay， Thank you
